apiVersion: v1
kind: Service
metadata:
  name: registration-service
spec:
  type: LoadBalancer # Or NodePort
  selector:
    app: registration-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
